pub const PROTOCOL_VERSION: u32 = 1;
pub const CONTRACT_DOCUMENTS_PATH_HEIGHT: u16 = 4;
pub const BASE_CONTRACT_ROOT_PATH_SIZE: u32 = 33; // 1 + 32
pub const BASE_CONTRACT_KEEPING_HISTORY_STORAGE_PATH_SIZE: u32 = 34; // 1 + 32 + 1
pub const BASE_CONTRACT_DOCUMENTS_KEEPING_HISTORY_STORAGE_TIME_REFERENCE_PATH: u32 = 75;
pub const BASE_CONTRACT_DOCUMENTS_KEEPING_HISTORY_PRIMARY_KEY_PATH_FOR_DOCUMENT_ID_SIZE: u32 = 67; // 1 + 32 + 1 + 1 + 32, then we need to add document_type_name.len()
pub const BASE_CONTRACT_DOCUMENTS_PATH: u32 = 34;
pub const BASE_CONTRACT_DOCUMENTS_PRIMARY_KEY_PATH: u32 = 35;
pub const DEFAULT_HASH_SIZE: u32 = 32;
pub const SOME_TREE_SIZE: Option<u16> = Some(32);
pub const SOME_OPTIMIZED_DOCUMENT_REFERENCE: Option<u16> = Some(34); // 1 + hops + DEFAULT_HASH_SIZE
pub const DEFAULT_FLOAT_SIZE: u32 = 8;
pub const EMPTY_TREE_STORAGE_SIZE: u32 = 33;
pub const MAX_INDEX_SIZE: usize = 255;
pub const STORAGE_FLAGS_SIZE: u32 = 2;

pub const CONTRACT_MAX_SERIALIZED_SIZE: u16 = 16384;
// TODO: Insert correct value here
pub const MAX_ELEMENT_SIZE: u32 = 5000;
